manifest = "b6249a5c295ebc6ea68a8a0f89e59374caf4ed1ba663a5815b2ceca64a88bd16"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
target = "//:predef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-ratio"
target = "//:ratio"

[[dependency]]
package = "github.com/buckaroo-pm/boost-rational"
target = "//:rational"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static-assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-system"
target = "//:system"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type-traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
target = "//:typeof"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[[dependency]]
package = "github.com/buckaroo-pm/boost-winapi"
target = "//:winapi"

[[lock]]
name = "github.com/buckaroo-pm/boost-assert"
revision = "cae7816110ba208a2290d02d128594e8809c9075"

[[lock]]
name = "github.com/buckaroo-pm/boost-config"
revision = "e60ff9d2778e3d2a6969859783a7c5bcc424f9a2"

[[lock]]
name = "github.com/buckaroo-pm/boost-core"
revision = "10b589cb4aea4ca823237059f104cbfdd09b0f0e"

[[lock]]
name = "github.com/buckaroo-pm/boost-detail"
revision = "94aa5268c1a74468be94b40afd730aea1730ceab"

[[lock]]
name = "github.com/buckaroo-pm/boost-exception"
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[[lock]]
name = "github.com/buckaroo-pm/boost-integer"
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[[lock]]
name = "github.com/buckaroo-pm/boost-move"
revision = "183c4c120078cc80bdc9fd4089d911aecd922aac"

[[lock]]
name = "github.com/buckaroo-pm/boost-mpl"
revision = "4c91f620f270414ceb5c3dbf3419a4f6ffe38c1e"

[[lock]]
name = "github.com/buckaroo-pm/boost-predef"
revision = "73def0812b7235e0312079c729342787819bf1d5"

[[lock]]
name = "github.com/buckaroo-pm/boost-preprocessor"
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[[lock]]
name = "github.com/buckaroo-pm/boost-ratio"
revision = "f1c61e4dd5f258c1f3b355a881f6048af1be5605"

[[lock]]
name = "github.com/buckaroo-pm/boost-rational"
revision = "0d7a63b2751677306b1a1e73b9aef6c91c564710"

[[lock]]
name = "github.com/buckaroo-pm/boost-static_assert"
revision = "4b9da4628bc69ad0e9b244d3ec885f2eadac95d8"

[[lock]]
name = "github.com/buckaroo-pm/boost-system"
revision = "0bd61d95858bdcaec79ffc47a76a4e01792238da"

[[lock]]
name = "github.com/buckaroo-pm/boost-throw_exception"
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[[lock]]
name = "github.com/buckaroo-pm/boost-type_traits"
revision = "a34caf51f831ffb77d1057c668b5db620863d191"

[[lock]]
name = "github.com/buckaroo-pm/boost-typeof"
revision = "18a9fd7819c36e3ff67a744c054cf144f3ca784c"

[[lock]]
name = "github.com/buckaroo-pm/boost-utility"
revision = "57aa216434800315c9cd2664169e444e3070a677"

[[lock]]
name = "github.com/buckaroo-pm/boost-winapi"
revision = "5b320a02051a6d1732335d5f12465fb0d99df086"
